### ISSUE TITLE
doesn't start on fresh install

### ISSUE THREAD

**Issue by tvogt** [pkcwong/meteor-react-starter#16]
console says:
There is no route for the path: /settings
kadira_flow-router.js:517:5

browser window remains empty.

**Comment by pkcwong** [comment]
@tvogt 
There is currently only one single route to ```/```.
Visiting ```localhost:3000/``` should render an empty page.
You may take [```/client/pages/navigator.jsx```](https://github.com/pkcwong/meteor-react-starter/blob/master/client/pages/navigator.jsx) as a reference on how to add new routes.
